version: '3.9'
name: 'geoscan'
        
services:
  geoscan:
    image: andrey-geoscan-test-docker
    container_name: geoscan
    command: ["/bin/bash", "-ci", "python3 main.py"]
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
    ipc: host
    stdin_open: true
    tty: true
    privileged: true
    network_mode: "host"
    # networks:
    #   - general
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - ./task_workspace:/task_workspace
